UI Card changes with accordian and buttons
p632-sp-2017/action-list pull request #11
Opened 2017-02-21 04:21 UTC by pandeyh92

Made UI changes over the panel.
Added buttons, accordion expansion of panel.
Please review and merge.

2017-02-21 05:29 UTC, PrashanthKumarM commented
Hey Hemanth, Please reverse merge develop to your branch to incorporate the new travis script changes

2017-02-21 14:50 UTC, burnumd requested changes

2017-02-21 14:50 UTC, burnumd commented on action_list_sample/action_list.js
> +
Don't include tabs on empty lines (there should be an option in your IDE of choice to automatically remove these).

2017-02-21 14:50 UTC, burnumd commented on action_list_sample/action_list.js
> +    actionButton: {
Inconsistent indentation

2017-02-21 14:50 UTC, burnumd commented on action_list_sample/panel.js
> +        let initialValue    = this.state.expanded? this.state.maxHeight + this.state.minHeight : this.state.minHeight,
If you're not going to modify these values, use `const` instead of `let`.

2017-02-21 14:50 UTC, burnumd commented on action_list_sample/panel.js
> +        finalValue      = this.state.expanded? this.state.minHeight : this.state.maxHeight + this.state.minHeight;
Use one declaration per variable: https://github.com/airbnb/javascript#variables--one-const

2017-02-21 14:50 UTC, burnumd commented on action_list_sample/panel.js
> +        this.setState({
None of these functions have test coverage.

2017-02-21 22:24 UTC, burnumd requested changes

2017-02-21 22:24 UTC, burnumd commented on action_list_sample/action_list.js
> +                title='Take Action'  />
Why are these properties split onto multiple lines?

2017-02-21 22:24 UTC, burnumd commented on action_list_sample/action_list.js
> +
This whitespace is unnecessary

2017-02-21 22:24 UTC, burnumd commented on action_list_sample/action_list.js
> +                title='Route Log' style={styles.routeButton}/>
1. `style` should appear on the next line if you're breaking up the properties (I'm not sure it's necessary) https://github.com/airbnb/javascript/tree/master/react#alignment
1. There should be a space before the `/` https://github.com/airbnb/javascript/tree/master/react#alignment

2017-02-21 22:24 UTC, burnumd commented on action_list_sample/action_list.js
> +        <View>
Fix indentation (as well as in the closing tag for this `View`)

2017-02-21 22:24 UTC, burnumd commented on action_list_sample/panel.js
> +                <View style={styles.titleContainer} onLayout={this._setMinHeight.bind(this)}>
Don't bind in a property or you'll be creating a new function every time the state/props change.

2017-02-22 15:19 UTC, burnumd requested changes
Use soft tabs set to two spaces (there should be a setting in your IDE to default this behavior per file extension): https://github.com/airbnb/javascript#whitespace--spaces

2017-02-22 21:56 UTC, burnumd approved these changes

2017-02-22 22:06 UTC, burnumd requested changes

2017-02-22 22:06 UTC, burnumd commented on 12
> +Merge branch 'test' of https://github.com/p632-sp-2017/action-list into develop
Looks like a commit message got committed as a file.

2017-02-22 22:06 UTC, burnumd commented on action_list_sample/header.js
> +// const style = StyleSheet.create({
If this stylesheet isn't needed, remove it (it will remain in the commit history if you need to get it back).

2017-02-22 22:06 UTC, burnumd commented on action_list_sample/header.js
> +});
Remove the extra whitespace and make sure there is a newline at the end of every file.

2017-02-27 23:03 UTC, PrashanthKumarM commented on action_list_sample/action_list.js
> +        <View>
Fixed these after integrating lint

2017-02-27 23:16 UTC, burnumd requested changes

2017-02-27 23:16 UTC, burnumd commented on actionlist/index.ios.js
> +/* eslint-disable */
Why are you disabling linting on an entire file? ESLint supports both single-line and rule-specific disables. In either case, any time you disable linting there should be a very good explanation in the comments to describe why.

2017-02-27 23:16 UTC, burnumd commented on actionlist/index.ios.js
> +
Remove the single space character on this empty line.

2017-02-27 23:16 UTC, burnumd commented on actionlist/__tests__/index.android.js
> +/* eslint-disable */
Why are you disabling linting on the entire file (see other comment).

2017-02-27 23:16 UTC, burnumd commented on actionlist/__tests__/index.ios.js
> +/* eslint-disable */
Why are you disabling linting on the entire file (see other comment).

2017-02-27 23:18 UTC, PrashanthKumarM commented on actionlist/__tests__/index.ios.js
> +/* eslint-disable */
This wont be used and should be removed as ios app is not in there.

2017-02-27 23:18 UTC, PrashanthKumarM commented on actionlist/__tests__/index.android.js
> +/* eslint-disable */
No tests are present currently so we have not linted this. Stephen would be changing this in the testing branch changes

2017-03-01 19:33 UTC, PrashanthKumarM commented on 12
> +Merge branch 'test' of https://github.com/p632-sp-2017/action-list into develop
removed this file

2017-03-01 19:35 UTC, PrashanthKumarM commented on action_list_sample/header.js
> +// const style = StyleSheet.create({
Changed and new stylesheet added for the view. Linting complete

2017-03-01 19:35 UTC, PrashanthKumarM commented on action_list_sample/header.js
> +});
Completed

2017-03-01 19:41 UTC, burnumd approved these changes

2017-03-01 20:54 UTC, merged