new open link commit
p632-sp-2017/action-list pull request #38
Opened 2017-04-05 19:23 UTC by Nethracs

removed openlink branch, branched out from develop and added the changes.

2017-04-05 19:37 UTC, PrashanthKumarM approved these changes
Looks good to go

2017-04-05 20:45 UTC, burnumd commented on actionlist/app/components/action_item_body.js
> +/* eslint no-underscore-dangle: ["error", { "allow": ["_links"] }] */
This eslint directive should appear closer to where it is used (and re-enabled ASAP).

2017-04-06 02:18 UTC, burnumd requested changes

2017-04-06 02:18 UTC, burnumd commented on actionlist/app/components/action_item_body.js
> +
Remove this extra whitespace, please.

2017-04-06 18:01 UTC, burnumd commented on actionlist/app/components/action_item_body.js
> +export default ActionItemBody;
Add a newline at the end of this file, please.

2017-04-06 18:03 UTC, burnumd approved these changes

2017-04-06 18:10 UTC, merged