Filtering
p632-sp-2017/action-list pull request #59
Opened 2017-04-20 04:11 UTC by PrashanthKumarM

3 filters implemented. The ones based on list options (documentRouteStatus, documentType and actionRequested)

2017-04-20 04:25 UTC, Nethracs commented on actionlist/app/components/SideMenu.js
> +/* eslint-enable no-unused-vars */
Remove this eslint exception

2017-04-20 04:26 UTC, PrashanthKumarM commented on actionlist/app/components/SideMenu.js
> +/* eslint-enable no-unused-vars */
fixed!!

2017-04-20 04:36 UTC, Nethracs approved these changes

2017-04-20 14:08 UTC, burnumd requested changes
This PR looks good. If you would, please, just extract the repeated`<View style={style.header}><Text style={style.headerText}>{/* text */}</Text></View>` segments into a `Header` component so they can be reused consistently.

2017-04-20 15:41 UTC, burnumd requested changes

2017-04-20 15:41 UTC, burnumd commented on actionlist/app/components/contentHeader.js
> +    <Text style={style.headerText}>{title}</Text>
I'd recommend not using a `title` prop and just using the `children` prop. It looks like it's allowed for `Text` components to have node children, so if you just use children you can pass off prop validation to the react-native component and allow yourself more flexibility.

2017-04-21 16:12 UTC, PrashanthKumarM commented on actionlist/app/components/contentHeader.js
> +    <Text style={style.headerText}>{title}</Text>
I tried to use children and lint threw an error saying I need to have a prop validation for it

2017-04-21 16:16 UTC, burnumd commented on actionlist/app/components/contentHeader.js
> +    <Text style={style.headerText}>{title}</Text>
Yes, the type of `children` should be documented as `React.PropTypes.node`: https://github.com/yannickcr/eslint-plugin-react/issues/7

2017-04-21 19:10 UTC, burnumd approved these changes

2017-04-21 19:12 UTC, merged