#56 preferences styling
p632-sp-2017/action-list pull request #60
Opened 2017-04-20 20:36 UTC by PrashanthKumarM

Fixed build as well

2017-04-20 21:00 UTC, burnumd requested changes

2017-04-20 21:00 UTC, burnumd commented on .travis.yml
> +  - cd actionlist && rm -rf node_modules && npm install
Why are you having to do these steps in CI? Is it related to [this](https://github.com/petester42/jest-preset-typescript-react-native/issues/1)? If so, updating to the latest `react-native` may help. I'd hate to see workarounds for something that's fixed (and if that doesn't fix it, it needs a comment about why this workaround is present).

2017-04-20 21:00 UTC, burnumd commented on actionlist/app/reducers/action_items.js
> -    saved: Colors.White,
What's the purpose of these changes? Having capitalized object keys seems pretty non-standard.

2017-04-20 22:52 UTC, PrashanthKumarM commented on .travis.yml
> +  - cd actionlist && rm -rf node_modules && npm install
Hi @burnumd it seems to be a problem with react-native-router-flux. It has its own react-native in its node_modules. While the line highlighted here is not needed, the line after this is needed. The @providesModule takes the reference of both the react-natives and says there is a collision. Deleting the node_module of react native router flux solves the problem

2017-04-20 22:55 UTC, PrashanthKumarM commented on .travis.yml
> +  - cd actionlist && rm -rf node_modules && npm install
Both the pull requests have the same problem with the build and I guess all the further builds will have it too. I am not able to figure out the root cause to this.

2017-04-21 15:59 UTC, PrashanthKumarM commented on actionlist/app/reducers/action_items.js
> -    saved: Colors.White,
changes made

2017-04-21 16:00 UTC, PrashanthKumarM commented
@burnumd The code climate issues are not valid. They are propType validations for 2 different elements

2017-04-21 16:37 UTC, PrashanthKumarM commented on .travis.yml
> +  - cd actionlist && rm -rf node_modules && npm install
@burnumd is it not ok to just delete the node modules folder? Our changes had no effect in the build failing.

2017-04-21 16:38 UTC, PrashanthKumarM commented on .travis.yml
> +  - cd actionlist && rm -rf node_modules && npm install
correction: node_modules folder inside react-native-router-flux

2017-04-21 16:46 UTC, burnumd commented on .travis.yml
> +  - cd actionlist && rm -rf node_modules && npm install
In that case, there should be a comment explaining why file system operations are occurring, hopefully with a link to an outstanding issue in the offending dependency. In this case: https://github.com/facebook/jest/issues/2070

2017-04-21 16:51 UTC, burnumd requested changes

2017-04-21 16:51 UTC, burnumd commented on actionlist/app/reducers/action_items.js
> +    Saved: 'white',
Wait, why does this no longer use `Colors.white`?

2017-04-21 16:51 UTC, burnumd commented on actionlist/app/reducers/action_items.js
> +    Saved: 'white',
Why do these no longer use `Colors.white`?

2017-04-21 16:51 UTC, burnumd commented on actionlist/package.json
> +    "react-native-button": "^1.8.2"
Does this dependency need to be a production dependency?

2017-04-21 17:12 UTC, PrashanthKumarM commented on actionlist/package.json
> +    "react-native-button": "^1.8.2"
moved to dev dependency

2017-04-21 17:12 UTC, PrashanthKumarM commented on actionlist/app/reducers/action_items.js
> +    Saved: 'white',
changed to Colors.white

2017-04-21 17:37 UTC, burnumd approved these changes

2017-04-21 18:12 UTC, merged